# Generated by Django 3.1.4 on 2021-04-18 06:43

from django.db import migrations, models
import eshope_products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discription', models.TextField(verbose_name='توضیحات')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshope_products.models.upload_image_path, verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
        ),
    ]
