# Generated by Django 3.1.4 on 2021-04-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshope_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
