# Generated by Django 3.1.4 on 2021-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshope_products_category', '0001_initial'),
        ('eshope_products', '0002_auto_20210418_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshope_products_category.Product_categories', verbose_name='دسته بندی'),
        ),
    ]
