# Generated by Django 3.1.4 on 2021-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshope_Subcategory', '0001_initial'),
        ('eshope_products', '0004_auto_20210419_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='eshope_Subcategory.Product_subcategories', verbose_name='زیردسته بندی'),
        ),
    ]
