# Generated by Django 3.1.4 on 2021-04-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshope_products', '0007_products_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='date',
        ),
    ]
