# Generated by Django 3.1.4 on 2021-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshope_products', '0009_products_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seen',
            field=models.IntegerField(default=0, verbose_name='بازدید فیک'),
        ),
    ]
