# Generated by Django 3.1.4 on 2021-04-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshope_products_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_subcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام زیردسته بندی')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان در url')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='eshope_products_category.Product_categories', verbose_name='دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'زیردسته بندی ',
                'verbose_name_plural': ' زیردسته بندی ها',
            },
        ),
    ]
