# Generated by Django 3.1.4 on 2021-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshope_products_category', '0001_initial'),
        ('eshope_Subcategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_subcategories',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshope_products_category.Product_categories', verbose_name='دسته بندی اصلی'),
        ),
    ]
