# Generated by Django 3.1.4 on 2021-04-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshope_Subcategory', '0002_auto_20210419_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_subcategories',
            old_name='categories',
            new_name='subcategories',
        ),
    ]
